### PR TITLE
Webpack

### PR DESCRIPTION
**Pull request by loaded02**

### CODE REVIEW

**Comment by loaded02** [comment]
Metric #2: Size
Transfer size is from the Chrome network tab. GZIPed response headers plus the response body, as delivered by the server.
```au run --env prod```
requirejs: vendor-bundle.js 428KB + app-bundle.js 51.1KB = 479.1KB
webpack: app-bundle.js 180B (on Network tab) BUT 458.2KB on Harddisk?!?

This is quite a difference. can someone confirm this? And since lighthouse isnt working on my machine does anyone want to measure the performance? First meaningful paint test with Lighthouse Audit that ships with Chrome. Maybe @4imble or @vegarringdal?

Anyways it looks like webpack with date-fns instead of moment.js is in the worst case still 20KB smaller.

**Comment by vegarringdal** [comment]
Sounds like its just cached
Disable cache and reload page

image

Would guess you get the gzipped to 150-180KB but not 180B
Did you do a type KB <> B

**Comment by vegarringdal** [comment]
On my private project(mframejs)
https://github.com/mframejs/mframejs-realworld-example-app

Ggipped takes it from 191KB on disk to 42.3 KB

image


Unminified/uglified and no code splitting my mframejs "real world app" is 429KB

**Comment by loaded02** [comment]
Shame on me. It was cached. Webpack is 458KB in size which saves 20KB compared to requirejs with momentjs. 
@vegarringdal  I have to check why current demo is so small. It should be 479KB. And how do you enable gzipped? Minification is in the default task for prod build in aurelia cli.

**Comment by vegarringdal** [comment]
@loaded, first link/pictures was just to show you the cache part, links to the other realworld is a mini framework I created for fun :-)
The last picture was aurelia live demo, it gets gzipped, so 120 is good, you might be lower with last improvements u have made.

**Comment by loaded02** [comment]
@vegarringdal  Ok then gzipped is done by gh-pages probably. Cause files on the server are larger. No things make sense again. ^^

**Comment by vegarringdal** [comment]
:-)

**Pull request merged**
